"""Add remarks to interview_marks

Revision ID: 5726ceeb9bb7
Revises: g1h2i3j4k5l6
Create Date: 2026-07-14 11:09:56.493742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5726ceeb9bb7'
down_revision: Union[str, None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_marks', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_marks', 'remarks')
    # ### end Alembic commands ###
