"""add ai fields to application

Revision ID: 5b227dcdfb81
Revises: b3c4d5e6f7a8
Create Date: 2026-04-26 01:01:16.687719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b227dcdfb81'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ai_status', sa.String(length=30), nullable=True))
    op.add_column('applications', sa.Column('ai_scrutiny_data', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('ai_confidence_score', sa.Integer(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('applications', 'ai_confidence_score')
    op.drop_column('applications', 'ai_scrutiny_data')
    op.drop_column('applications', 'ai_status')
    # ### end Alembic commands ###
