"""Add Step 2 tables and switch to async

Revision ID: 645eefca145f
Revises: 
Create Date: 2026-04-22 14:45:43.215537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645eefca145f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('existing_faculty',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_effective', sa.Boolean(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'employee_id', 'academic_year', name='_inst_employee_year_uc')
    )
    op.create_table('faculty_qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('year_of_passing', sa.Integer(), nullable=True),
    sa.Column('is_highest', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['existing_faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancy_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('total_existing', sa.Integer(), nullable=False),
    sa.Column('effective_existing', sa.Integer(), nullable=False),
    sa.Column('suggested_vacancy', sa.Integer(), nullable=False),
    sa.Column('confirmed_vacancy', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ai_suggestion_notes', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['faculty_requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'course_id', 'academic_year', name='_inst_branch_year_uc')
    )
    op.create_table('vacancy_anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['vacancy_assessments.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['existing_faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_anomalies')
    op.drop_table('vacancy_assessments')
    op.drop_table('faculty_qualifications')
    op.drop_table('existing_faculty')
    # ### end Alembic commands ###
