"""Add advertisement detail columns

Revision ID: 816930c3f92d
Revises: 5b227dcdfb81
Create Date: 2026-04-26 20:04:50.702640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816930c3f92d'
down_revision: Union[str, None] = '5b227dcdfb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('qualification_requirements', sa.Text(), nullable=True))
    op.add_column('advertisements', sa.Column('required_documents', sa.Text(), nullable=True))
    op.add_column('advertisements', sa.Column('important_instructions', sa.Text(), nullable=True))
    op.add_column('advertisements', sa.Column('interview_venue', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'interview_venue')
    op.drop_column('advertisements', 'important_instructions')
    op.drop_column('advertisements', 'required_documents')
    op.drop_column('advertisements', 'qualification_requirements')
    # ### end Alembic commands ###
