"""implement_step5_selection_models

Revision ID: 91eaa9285cf0
Revises: 2f4d8dbf5a11
Create Date: 2026-04-23 15:57:26.126054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91eaa9285cf0'
down_revision: Union[str, None] = '2f4d8dbf5a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_weight_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_name', sa.String(length=100), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('advertisement_id', sa.UUID(), nullable=True),
    sa.Column('qualification_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interview_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('publication_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reservation_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('set_by_role', sa.String(length=30), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selection_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('advertisement_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('advertisement_id', 'round_type', name='_sel_round_type_uc')
    )
    op.create_table('candidate_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('qualification_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('interview_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('publication_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reservation_tiebreaker', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['selection_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'application_id', name='_cand_score_round_app_uc')
    )
    op.create_table('interview_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('subject_knowledge', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('teaching_aptitude', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('communication_skills', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overall_impression', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interview_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['selection_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'application_id', name='_int_marks_round_app_uc')
    )
    op.create_table('selection_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('result_status', sa.String(length=30), nullable=False),
    sa.Column('waitlist_position', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['selection_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'candidate_id', name='_sel_result_round_cand_uc')
    )
    op.create_table('shortlisted_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('shortlisted_by', sa.Integer(), nullable=True),
    sa.Column('shortlist_remarks', sa.Text(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['selection_rounds.id'], ),
    sa.ForeignKeyConstraint(['shortlisted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'application_id', name='_shortlist_round_app_uc')
    )
    op.add_column('vacancy_anomalies', sa.Column('round_id', sa.UUID(), nullable=True))
    op.alter_column('vacancy_anomalies', 'assessment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'vacancy_anomalies', 'selection_rounds', ['round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy_anomalies', type_='foreignkey')
    op.alter_column('vacancy_anomalies', 'assessment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('vacancy_anomalies', 'round_id')
    op.drop_table('shortlisted_candidates')
    op.drop_table('selection_results')
    op.drop_table('interview_marks')
    op.drop_table('candidate_scores')
    op.drop_table('selection_rounds')
    op.drop_table('scoring_weight_configs')
    # ### end Alembic commands ###
