"""Add liveness engine fields

Revision ID: 9b9c5b09d87c
Revises: aebd3f748181
Create Date: 2026-07-01 17:47:18.232119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9c5b09d87c'
down_revision: Union[str, None] = 'aebd3f748181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection_rounds')
    op.add_column('faculty_credentials', sa.Column('face_embedding', sa.String(), nullable=True))
    op.add_column('faculty_credentials', sa.Column('face_registered', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('faculty_credentials', 'appointment_letter_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('faculty_credentials', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('faculty_credentials', 'existing_faculty_id')
    op.add_column('lecture_logs', sa.Column('liveness_score', sa.Float(), nullable=True))
    op.add_column('lecture_logs', sa.Column('face_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.create_foreign_key(None, 'lecture_logs', 'timetable_slots', ['timetable_slot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lecture_logs', type_='foreignkey')
    op.drop_column('lecture_logs', 'face_verified')
    op.drop_column('lecture_logs', 'liveness_score')
    op.add_column('faculty_credentials', sa.Column('existing_faculty_id', sa.UUID(), autoincrement=False, nullable=True))
    op.alter_column('faculty_credentials', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('faculty_credentials', 'appointment_letter_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('faculty_credentials', 'face_registered')
    op.drop_column('faculty_credentials', 'face_embedding')
    op.create_table('selection_rounds',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('advertisement_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('academic_year', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('round_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisements.id'], name='selection_rounds_advertisement_id_fkey'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='selection_rounds_course_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='selection_rounds_created_by_fkey'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name='selection_rounds_institution_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='selection_rounds_pkey'),
    sa.UniqueConstraint('advertisement_id', 'round_type', name='_sel_round_type_uc')
    )
    # ### end Alembic commands ###
